version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      # Must match package.json "engines.vscode" value
      - dependency-name: "@types/vscode"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
