on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  packages: write

name: Release Please

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Release-Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

      - name: Install Node.js
        if: ${{ steps.release.outputs.release_created == 'true' }}
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "npm"

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created == 'true' }}
        run: npm ci

      - name: Build and publish on VS Code Marketplace
        if: ${{ steps.release.outputs.release_created == 'true' }}
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Build and publish on Open VSX Registry
        if: ${{ steps.release.outputs.release_created == 'true' }}
        run: |
          jq -r 'del(.extensionDependencies)' package.json > package.tmp && mv package.tmp package.json
          npm run deploy:ovsx
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
